apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Chart.Name | trimSuffix "-chart" }}
  name: {{ .Chart.Name | trimSuffix "-chart" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "5000"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    service: {{ .Chart.Name | trimSuffix "-chart" }}
